#deployer is address of the contract deployer (who often is privileged owner, etc.)
deployer: "0x41414141"
#sender is set of addresses transactions may originate from
sender: ["0x42424242", "0x43434343"]
#maximum time between generated txs; default is one week
maxTimeDelay: 15778800
#testLimit is the number of test sequences to run
testLimit: 1000000
#seqLen defines how many transactions are in a test sequence
seqLen: 200
#coverage controls coverage guided testing
coverage: false
#checkAsserts checks assertions
checkAsserts: true
#map dependencies
cryticArgs:
  [
    "--solc-remaps",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
  ]